;  Host side configuration file for source level debug support.
;
;  Copyright (c) 2010 - 2015, Intel Corporation. All rights reserved. <BR>
;  This software and associated documentation (if any) is furnished
;  under a license and may only be used or copied in accordance
;  with the terms of the license. Except as permitted by such
;  license, no part of this software or documentation may be
;  reproduced, stored in a retrieval system, or transmitted in any
;  form or by any means without the express written consent of
;  Intel Corporation.

[Debug Port]
Channel = Pipe
Port = QemuPipeDbg
FlowControl = 1
BaudRate = 115200
Server = 

[Target System]
; Debugger needs to know the target processor count in the initialization step.
;  Use a value larger enough.
ProcessorCount = 16
FlashRange        = 0xFF000000:0x1000000
;TemporaryRamRange = 0x80000000:0x80000
NoAccessLimit     = 0x80000000

[Debugger]
Executable = C:\Program Files (x86)\Debugging Tools for Windows (x86)\windbg.exe
Directory = C:\Program Files (x86)\Debugging Tools for Windows (x86)

[Features]
; Have WinDbg to load the module symbols when the module is loaded in target,
;  which enables to set unresolved breakpoints.
LoadModuleSymbol = 1

TerminalRedirectionPort = 20715

; Specify the alternative symbol path search path if the symbol file is moved
; SymbolPath = C:\Build;D:\Build

[Maintenance]
; Uncomment the below line to turn on tracing
; Trace=0x1f

; The time to delay between the debugger's reset on the target system and the
;  start of the WinDbg session's setup on the host.
; ResetDelay = 10

; The warning count when debugger cannot resolve the symbol path.
; WarningOnUnresolvedSymbolPath = 2
